#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
import os
import glob
import argparse
import subprocess
import re
import shutil
from pathlib import Path

def main():
    """
    Main function to find FAA files and run InterProScan on them.
    """
    # === Argument Parsing ===
    parser = argparse.ArgumentParser(
        description="Run InterProScan on FAA files generated by the extract step.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument('--base-dir', type=str, required=True,
                        help="The base directory for a specific sample (e.g., 'depression/'). Required.")
    parser.add_argument('--interproscan-dir', type=str,
                        help="Path to the InterProScan directory. If not provided, it will be auto-detected under '<project_root>/tools/'.")
    parser.add_argument('--cpu', type=int, default=8,
                        help="Number of CPU cores for InterProScan to use.")
    parser.add_argument('--appl', type=str, default='TIGRFAM,SUPERFAMILY,PANTHER,Gene3D,Hamap,ProSiteProfiles,SMART,CDD,PRINTS,PIRSR,ProSitePatterns,Pfam',
                        help="Comma-separated list of applications for InterProScan.")
    
    args = parser.parse_args()

    # === Path Configuration ===
    base_dir = Path(args.base_dir).resolve()
    if not base_dir.is_dir():
        print(f"Error: --base-dir '{args.base_dir}' not found or not a directory.", file=sys.stderr)
        sys.exit(1)
        
    project_root = base_dir.parent

    # --- Find InterProScan executable ---
    interproscan_script = None
    if args.interproscan_dir:
        interpro_dir = Path(args.interproscan_dir).resolve()
        interproscan_script = interpro_dir / 'interproscan.sh'
    else:
        # === ššš ‚±‚±‚©‚çC³ ššš ===
        # Auto-detection logic is improved to explicitly find directories.
        interpro_tools_dir = project_root / 'tools'
        
        # 1. Get all potential candidates (files and directories) matching the pattern.
        all_candidates = list(interpro_tools_dir.glob('interproscan-*'))
        
        # 2. Filter the list to keep only the directories.
        dir_candidates = [path for path in all_candidates if path.is_dir()]

        if not dir_candidates:
            print(f"Error: Could not find an UNCOMPRESSED interproscan directory under {interpro_tools_dir}", file=sys.stderr)
            print("Please make sure you have uncompressed the .tar.gz archive.", file=sys.stderr)
            sys.exit(1)
            
        # 3. Use the first valid directory found. Sort to be deterministic.
        interpro_dir = sorted(dir_candidates)[0]
        interproscan_script = interpro_dir / 'interproscan.sh'
        # === ššš ‚±‚±‚Ü‚ÅC³ ššš ===


    if not (interproscan_script.is_file() and os.access(interproscan_script, os.X_OK)):
        print(f"Error: '{interproscan_script}' does not exist or is not executable.", file=sys.stderr)
        sys.exit(1)
        
    print(f"Using InterProScan at: {interproscan_script}")

    # === Find and Process FAA files ===
    levels = ['Class', 'Order', 'Family', 'Genus', 'Species']
    done_basename = {}

    for level in levels:
        glob_pattern = str(base_dir / f"{level}_*/faa/*.faa")
        faa_files = glob.glob(glob_pattern)

        for input_path_str in faa_files:
            input_path = Path(input_path_str)
            
            class_dir = input_path.parent.parent
            file_name = input_path.name
            basename = input_path.stem

            interpro_out_dir = class_dir / 'interpro'
            interpro_out_dir.mkdir(exist_ok=True)
            output_path = interpro_out_dir / f"{basename}.tsv"

            if output_path.exists():
                print(f"[?] Found existing InterProScan output for {basename} -> skipping.")
                if basename not in done_basename:
                    done_basename[basename] = str(output_path)
                continue

            if basename in done_basename:
                source_path = done_basename[basename]
                print(f"[->] Copying result for {basename} from {source_path} to {output_path}")
                try:
                    shutil.copy(source_path, output_path)
                except Exception as e:
                    print(f"[!] Failed to copy {source_path} to {output_path}: {e}", file=sys.stderr)
                continue

            print(f"[*] Running InterProScan for {basename}")
            cmd = [
                str(interproscan_script),
                '-i', str(input_path),
                '-f', 'tsv',
                '-o', str(output_path),
                '--goterms',
                '-cpu', str(args.cpu),
                '-appl', args.appl,
            ]
            
            try:
                result = subprocess.run(cmd, capture_output=True, text=True)
                if result.returncode != 0:
                    print(f"[!] Failed to run InterProScan for {file_name}", file=sys.stderr)
                    if result.stderr:
                        print(f"[!] Stderr: {result.stderr.strip()}", file=sys.stderr)
                else:
                    done_basename[basename] = str(output_path)
            except Exception as e:
                print(f"[!] An unexpected error occurred while running InterProScan for {file_name}: {e}", file=sys.stderr)


    print("InterProScan processing finished.")

if __name__ == "__main__":
    main()