#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
import os
import re
import glob
import argparse
from pathlib import Path

# --- Helper Functions ---

def load_go_namespaces(obo_file_path):
    """
    Parses a go.obo file to create a mapping from GO ID to its namespace.
    e.g., {'GO:0008150': 'biological_process'}
    """
    if not obo_file_path.is_file():
        print(f"Warning: GO OBO file not found at {obo_file_path}. GO types will be 'unknown'.", file=sys.stderr)
        return {}
        
    goid_to_namespace = {}
    with open(obo_file_path, 'r', encoding='utf-8') as f:
        current_goid = None
        for line in f:
            if line.startswith('id: '):
                current_goid = line.strip().split(' ')[1]
            elif line.startswith('namespace: ') and current_goid:
                namespace = line.strip().split(' ')[1]
                goid_to_namespace[current_goid] = namespace
                current_goid = None
    return goid_to_namespace

def select_sample_directory_for_extract():
    """
    Interactively selects a sample directory that is ready for the 'extract' step.
    A valid directory must contain 'assembly.done' and 'get_datasets.done' flags.
    """
    print("Searching for sample directories ready for extraction...")
    project_root = Path.cwd()
    candidate_dirs = []
    
    for d in project_root.iterdir():
        if d.is_dir():
            done_dir = d / "done"
            if done_dir.is_dir() and (done_dir / "assembly.done").is_file() and (done_dir / "get_datasets.done").is_file():
                candidate_dirs.append(d)

    if not candidate_dirs:
        print(f"Error: No directories ready for extraction found in {project_root}", file=sys.stderr)
        sys.exit(1)
        
    print("\nPlease choose the sample directory to process:")
    for i, directory in enumerate(candidate_dirs):
        print(f"  [{i + 1:2d}] {directory.name}")
    
    try:
        choice_str = input(f"\nEnter number (1-{len(candidate_dirs)}): ")
        choice = int(choice_str.strip())
        if 1 <= choice <= len(candidate_dirs):
            chosen_dir = candidate_dirs[choice - 1]
            print(f"-> Target directory set to '{chosen_dir.name}'.")
            return str(chosen_dir)
        else:
            raise ValueError("Choice out of range.")
    except (ValueError, EOFError, KeyboardInterrupt):
        print("\nInvalid selection or operation cancelled.", file=sys.stderr)
        sys.exit(1)

def find_assembly_tsvs(root_dir):
    """
    Recursively finds TSV files generated by the assembly step.
    """
    target_tsvs = []
    pattern = re.compile(r'^(Class|Genus|Family|Order|Species)_.+\.tsv$')
    for dirpath, _, filenames in os.walk(root_dir):
        for filename in filenames:
            if pattern.match(filename):
                target_tsvs.append(os.path.join(dirpath, filename))
    return target_tsvs

def parse_location_info(location_str):
    """
    Parses a GenBank location string.
    """
    strand = 'plus'
    if 'complement' in location_str:
        strand = 'minus'
    location_str = re.sub(r'complement|\(|\)|join|<|>', '', location_str)
    numbers = re.findall(r'\d+', location_str)
    begin, end = (numbers[0], numbers[-1]) if numbers else ('', '')
    return begin, end, strand

def main():
    """
    Main function to extract data from GBFF files.
    """
    # --- Jupyter/IPython Compatibility: Clean arguments before parsing ---
    cleaned_argv = []
    i = 0
    while i < len(sys.argv):
        arg = sys.argv[i]
        if arg in ['-f', '--f'] or ('kernel-' in arg and arg.endswith('.json')):
            if arg in ['-f', '--f']: i += 2
            else: i += 1
            continue
        cleaned_argv.append(arg)
        i += 1
    
    # --- Argument Parsing ---
    parser = argparse.ArgumentParser(
        description="Extracts features from GBFF files based on previous pipeline steps."
    )
    parser.add_argument('sample_output_directory', nargs='?', default=None,
                        help="Path to the sample's output directory. If omitted, interactive mode will start.")
    
    args = parser.parse_args(cleaned_argv[1:])
    sample_output_dir = args.sample_output_directory
    
    # --- Interactive Mode Fallback ---
    if not sample_output_dir:
        print("No sample directory provided via command line, entering interactive mode.")
        sample_output_dir = select_sample_directory_for_extract()

    if not os.path.isdir(sample_output_dir):
        print(f"Error: Sample output directory not found: {sample_output_dir}", file=sys.stderr)
        sys.exit(1)
    
    # --- Path and Data Setup ---
    project_root = Path.cwd()
    gbff_input_dir = project_root / "data" / "rawgbff"
    go_obo_path = project_root / "data" / "go.obo"
    
    print(f"? Reading GBFF files from: {gbff_input_dir}")
    print(f"? Loading GO definitions from: {go_obo_path}")
    goid_to_namespace = load_go_namespaces(go_obo_path)

    subdirs = {
        'faa': 'faa', 'go_annotations': 'go_annotations',
        'genomic_annotations': 'genomic_annotations', 'fasta': 'fasta',
    }
    
    # --- Main Processing Loop ---
    tsv_files = find_assembly_tsvs(sample_output_dir)
    if not tsv_files:
        print(f"Warning: No relevant TSV files found under {sample_output_dir}", file=sys.stderr)
        return

    for tsv_file in tsv_files:
        output_base_dir = os.path.dirname(tsv_file)
        print(f"Processing list: {tsv_file}")

        for subdir_name in subdirs.values():
            os.makedirs(os.path.join(output_base_dir, subdir_name), exist_ok=True)
            
        try:
            with open(tsv_file, 'r', encoding='utf-8') as fh:
                try:
                    next(fh)
                except StopIteration:
                    print(f"Warning: Skipping empty input file: {tsv_file}", file=sys.stderr)
                    continue

                for line in fh:
                    if not line.strip(): continue
                    cols = line.strip().split('\t')
                    gcf = cols[0]
                    if not re.match(r'^GC[AF]_\d+\.\d+$', gcf): continue
                    
                    glob_pattern = str(gbff_input_dir / f"*_{gcf}/ncbi_dataset/data/{gcf}/genomic.gbff")
                    gbff_files = glob.glob(glob_pattern)

                    if not gbff_files:
                        print(f"Warning: No .gbff file found for GCF: {gcf}", file=sys.stderr)
                        continue

                    for gbff_file in gbff_files:
                        faa_output_file = os.path.join(output_base_dir, subdirs['faa'], f"{gcf}.faa")
                        go_output_file = os.path.join(output_base_dir, subdirs['go_annotations'], f"{gcf}_go_annotations.tsv")
                        tsv_output_file = os.path.join(output_base_dir, subdirs['genomic_annotations'], f"{gcf}_genomic.tsv")
                        gcf_fasta_dir = os.path.join(output_base_dir, subdirs['fasta'], gcf)
                        os.makedirs(gcf_fasta_dir, exist_ok=True)

                        try:
                            with open(gbff_file, 'r', encoding='utf-8') as f_in, \
                                 open(faa_output_file, 'w', encoding='utf-8') as faa_out, \
                                 open(go_output_file, 'w', encoding='utf-8') as go_out, \
                                 open(tsv_output_file, 'w', encoding='utf-8') as tsv_out:
                                
                                go_out.write("Accession\tOrganism\tGO_ID\tGO_Type\n")
                                tsv_out.write("Accession\tOrganism\tBegin\tEnd\tStrand\tProduct\tGene\tLocus_Tag\tProtein_Length\tProtein_ID\n")
                                
                                content = f_in.read()
                                entries = content.split('//\n')

                                for entry in entries:
                                    if 'ACCESSION' not in entry: continue
                                    accession_match = re.search(r'^\s*ACCESSION\s+(\S+)', entry, re.MULTILINE)
                                    org_match = re.search(r'^\s*ORGANISM\s+([^\n]+)', entry, re.MULTILINE)
                                    if not (accession_match and org_match): continue
                                    accession, org = accession_match.group(1), org_match.group(1).strip()
                                    
                                    genomic_annotations = []
                                    cds_matches = re.finditer(r'^\s{5}CDS\s+(?P<location>[^\n]+)\n(?P<qualifiers>(?:^\s{6,}.*\n?)*)', entry, re.MULTILINE)
                                    
                                    for match in cds_matches:
                                        location_str, qualifiers_block = match.group('location'), match.group('qualifiers')
                                        begin, end, strand = parse_location_info(location_str)
                                        pid_match = re.search(r'\/protein_id="([^"]+)"', qualifiers_block)
                                        if not pid_match: continue
                                        protein_id = pid_match.group(1)
                                        prod_match = re.search(r'\/product="(.+?)"', qualifiers_block, re.DOTALL)
                                        product = prod_match.group(1).replace('\n', ' ').replace('  ', ' ').strip() if prod_match else 'unknown'
                                        gene_match = re.search(r'\/gene="([^"]+)"', qualifiers_block)
                                        gene = gene_match.group(1) if gene_match else 'unknown'
                                        locus_match = re.search(r'\/locus_tag="([^"]+)"', qualifiers_block)
                                        locus_tag = locus_match.group(1) if locus_match else 'unknown'
                                        trans_match = re.search(r'\/translation="(.+?)"', qualifiers_block, re.DOTALL)
                                        protein_length = 0
                                        if trans_match:
                                            translation = trans_match.group(1)
                                            clean_translation = re.sub(r'[\s"]', '', translation)
                                            protein_length = len(clean_translation)
                                            faa_out.write(f">{protein_id} [{org}] {product}\n{clean_translation}\n")
                                            fasta_file = os.path.join(gcf_fasta_dir, f"{protein_id}.fasta")
                                            with open(fasta_file, 'w', encoding='utf-8') as fasta_out:
                                                fasta_out.write(f">{protein_id} [{org}] {product}\n{clean_translation}\n")
                                        
                                        go_extra_matches = re.finditer(r'\/GO_(?:component|function|process)="GO:(\d+)|/db_xref="GO:(\d+)"', qualifiers_block)
                                        for go_match in go_extra_matches:
                                            go_id_num = go_match.group(1) or go_match.group(2)
                                            go_id_str = f"GO:{go_id_num}"
                                            namespace = goid_to_namespace.get(go_id_str, 'unknown')
                                            go_out.write(f'{protein_id}\t{org}\t{go_id_str}\t{namespace}\n')

                                        genomic_annotations.append([
                                            accession, org, begin, end, strand, product, gene, locus_tag, protein_length, protein_id
                                        ])
                                    for ann in genomic_annotations:
                                        tsv_out.write("\t".join(str(field or 'unknown') for field in ann) + "\n")
                                print(f"  -> Processed: {gbff_file}")
                        except Exception as e:
                            print(f"Error processing {gbff_file}: {e}", file=sys.stderr)
        except IOError as e:
             print(f"Error opening file {tsv_file}: {e}", file=sys.stderr)

    print("All files processed.")

if __name__ == "__main__":
    main()